version: "3.8"

services:
  strapi-lps:
    image: strapi/strapi
    env_file:
      - ./app/.env
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}

    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
    external: true
    name: local-network
